spring.application.name=S3DemoApplication
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}

aws.bucket.name=${AWS_BUCKET_NAME}
