spring.application.name=S3DemoApplication
cloud.aws.credentials.access-key=Your_Access_Key
cloud.aws.credentials.secret-key=Your_Secret_Key
cloud.aws.region.static=ap-south-2

aws.bucket.name=sivakrishnabucketv1
